module.exports = {

    jwt_error: 'Jwt Error.',
    invalid_credentials: 'Invalid credentials or please register to login',
    logged_in: 'Logged in successfully.',
    db_error: 'Database query error.',
    invalid_token: 'Invalid token.',
    view_vendor: 'Vendor details has been fetched.',
    vendor_created: 'Vendor created successfully.',
    user_exists: 'User already exists.',
    vendor_list: 'Vendor list has been fetched.',
    detail_updated: 'Details updated successfully.',
    user_not_exists: 'User does not exist.',
    user_logout: 'User logged out successfully.',
    invalid_user: 'User not found.',
    data_not_present: 'Data for this id is not present.',
    data_retrieved: 'Data retrieved.',
    otpGenerated: 'OTP has been generated.',
    user_deleted: 'User deleted successfully.',
    upload_error: 'Error in uploading image.',
    signed_error: 'Error in generating the signed URL.',
    view_product: 'Product details has been fetched.',
    product_created : 'Product has been created successfully.',
    product_deleted: 'Product deleted successfully.',
    product_list : 'Product list has been fetched.',
    view_vendor_user : 'Vendor user details has been fetched',
    invalid_user_type : 'The user is not superadmin',
    user_list : 'User list has been fetched',
    view_restaurant: 'Restaurant details has been fetched.',
    restaurant_list : 'Restaurant list has been fetched',
    restaurant_created: 'Restaurant created successfully.',
    view_user :'User details has been fetched',
    user_created : 'User added sucessfully',
    view_note: 'Note has been fetched.',
};